---
# tasks file for docker_nginx_proxy
# For accessing containerized services from outside the host using
# friendly DNS names as well as SSL/TLS termination.

- name: ensure directory for TLS certs for proxied containers exists
  sudo: true
  file:
    path: "{{ dnp_nginx_certs_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: ensure directory for per-vhost nginx configs exists
  sudo: true
  file:
    path: "{{ dnp_nginx_vhost_dir }}"
    state: directory
    owner: root
    group: docker
    mode: 02775

- name: nginx based reverse proxy
  docker:
    image: jwilder/nginx-proxy
    name: yxorp
    ports: ['80:80', '443:443']
    volumes:
      - "{{ dnp_nginx_certs_dir }}:/etc/nginx/certs"
      - "{{ dnp_nginx_vhost_dir }}:/etc/nginx/vhost.d:ro"
      - '/var/run/docker.sock:/tmp/docker.sock'
